services:
  web:
    build: .
    env_file: .env
    ports:
      - "${PORT:-8082}:8080"
    depends_on:
      - redis
    command: uvicorn src.main:app --host 0.0.0.0 --port 8080

  worker:
    build: .
    env_file: .env
    depends_on:
      - redis
    command: celery -A src.core.celery_app worker --loglevel=info --concurrency=2

  redis:
    image: redis:7-alpine
    volumes: ["redis_data:/data"]

volumes:
  redis_data: