version: '3.9'

services:
  web:
    build: .
    env_file: .env
    ports:
      - "8082:8080"  # Cambiado para coincidir con ngrok
    depends_on:
      - redis
      - db

  worker:
    build: .
    env_file: .env
    depends_on:
      - redis
      - db
    command: celery -A src.tasks worker --loglevel=info

  redis:
    image: redis:7-alpine
    volumes: ["redis_data:/data"]

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  redis_data:
  pg_data:
  postgres_data: