[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn src.main:app --host 0.0.0.0 --port $PORT"
# Si el comando de arriba falla, prueba este:
# startCommand = "python start.py"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ["python311", "postgresql"]

[[env]]
key = "PYTHON_PATH"
value = "."

[[env]]
key = "PYTHONPATH"
value = "."

[[env]]
key = "DB_SSL_MODE"
value = "require"

[[env]]
key = "PYTHONUNBUFFERED"
value = "1"
