[build]
builder = "nixpacks"
buildCommand = """
    mkdir -p /app && \
    cp -r . /app/ && \
    cd /app && \
    pip install -r requirements.txt
"""

[deploy]
startCommand = "cd /app && python -m uvicorn main:app --host 0.0.0.0 --port=${PORT:-8000}"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ["python311", "postgresql"]

[[env]]
key = "PYTHON_PATH"
value = "."

[[env]]
key = "PYTHONPATH"
value = "."

[[env]]
key = "DB_SSL_MODE"
value = "require"

[[env]]
key = "PYTHONUNBUFFERED"
value = "1"
