[build]
builder = "nixpacks"
buildCommand = """
    pip install --upgrade pip && \
    pip install -r requirements.txt && \
    echo '#!/bin/bash' > start.sh && \
    echo 'PORT="${PORT:-8000}"' >> start.sh && \
    echo 'exec uvicorn main:app --host 0.0.0.0 --port "$PORT" --workers 4' >> start.sh && \
    chmod +x start.sh && \
    ls -la start.sh
"""

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ["python311", "postgresql", "curl"]

[[env]]
key = "DB_SSL_MODE"
value = "require"

[[env]]
key = "PYTHONUNBUFFERED"
value = "1"
