[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -c 'from main import start_server; start_server()'"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ["python311", "postgresql"]

[[env]]
key = "PYTHONPATH"
value = "/app"

[[env]]
key = "DB_SSL_MODE"
value = "require"

[[env]]
key = "PYTHONUNBUFFERED"
value = "1"
