[build]
builder = "nixpacks"
buildCommand = """
    pip install --upgrade pip && \
    pip install -r requirements.txt && \
    mkdir -p /app && \
    cp -r . /app/
"""

[deploy]
startCommand = "cd /app && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ["python311", "postgresql"]

[[env]]
key = "DB_SSL_MODE"
value = "require"

[[env]]
key = "PYTHONUNBUFFERED"
value = "1"
