#!/bin/bash
echo "🌐 Configurando ngrok para webhooks..."
echo ""
echo "Asegúrate de tener ngrok instalado: https://ngrok.com/download"
echo ""
echo "Ejecuta este comando en una nueva terminal:"
echo ""
echo "ngrok http 8080"
echo ""
echo "Luego copia la URL HTTPS que te proporciona (algo como https://abc123.ngrok.io)"
echo "Y úsala para configurar el webhook en Meta"
echo ""
echo "La URL del webhook será: https://tu-dominio.ngrok.io/webhook"
echo ""
echo "📝 Pasos en Meta:"
echo "1. Ve a tu app en developers.facebook.com"
echo "2. WhatsApp > Configuración"
echo "3. Webhook URL: https://tu-dominio.ngrok.io/webhook"
echo "4. Verify Token: 13"
echo "5. Suscríbete al campo 'messages'" 